---
info:
  description: Training configuration repo

---
spring
 profiles: cloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_rscale:i_am_eureka!@eureka-server-theogonic-polydemonist.cfapps.io/eureka
