---
spring:
 profiles: cloud

eureka:
 client:
  serviceUrl:
   defaultZone: http://eureka_rscale:i_am_eureka!@eureka-server-theogonic-polydemonist.cfapps.io/eureka
 instance:
  hostname: ${vcap.application.uris[0]}
  nonSecurePort: 80
